server:
  port: 9999


spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/BloodFlame/spring-cloud-config.git
          timeout: 60
          default-label: master
          force-pull: true
          username: BloodFlame
          password: XinGXinG123
          search-paths: /local
    bus:
      refresh:
        enabled: true
      enabled: true
  application:
    name: config-center
  rabbitmq:
    host: 192.168.99.100
    port: 5672
    username: guest
    password: guest

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8000/eureka
  instance:
    prefer-ip-address: true
    instance-id: config-server:9999

management:
  endpoints:
    web:
      exposure:
        include: '*'